mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('salary/', include('salary.urls')),
    path('admin/', admin.site.urls),
    url(r'', include('salary.urls')),  # home page
]

mysite/salary/urls.py
from django.urls import path
from . import views as views

app_name = 'salary'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('new-user/', views.new_user, name='new-user'),
    path('<str:username>/new-profile/', views.new_profile, name='new-profile'),
    path('logout/', views.logout, name='logout'),
    path('change-payment/', views.change_payment, name='change-payment'),
    path('add-shifts/', views.add_shifts, name='add-shifts'),
    path('not-success/', views.not_success, name='not-success'),
    path('my-shifts/', views.my_shifts, name='my-shifts'),
    path('choose-month/', views.choose_month, name='choose-month'),
    path('remove-shifts/', views.remove_shifts, name='remove-shifts'),
]

mysite/salary/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class Users(models.Model):
    user_id = models.CharField(max_length=50)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    age = models.IntegerField(default=0)
    address = models.CharField(max_length=100, default="")
    is_admin = models.BooleanField(default=False)
    payment = models.IntegerField(default=29)


    def __str__(self):
        return str(self.user)

class Shifts(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True, default=1)
    date = models.DateField()
    start = models.TimeField()
    over = models.TimeField()
    percent100 = models.IntegerField(default=0)
    percent125 = models.IntegerField(default=0)
    percent150 = models.IntegerField(default=0)
    percent175 = models.IntegerField(default=0)
    percent200 = models.IntegerField(default=0)
    total_time = models.FloatField(default=0)
    total_money = models.FloatField(default=0)
    bonus = models.IntegerField(default=0)
    comment = models.CharField(max_length=1000, blank=True)
#    rest = models.BooleanField(default=False)

    def __str__(self):
        return str(self.date)

mysite/salary/forms.py
import self as self
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, Shifts


class LoginForm(forms.Form):
    user_name = forms.CharField(initial='')
    password = forms.CharField(widget=forms.PasswordInput(), initial='')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('address', 'age', 'payment')
        
        
class CompleteUserForm(UserCreationForm):  # create user - django
    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2',
                  )

        def save(self, commit=True):
            user = super(CompleteUserForm, self).save(commit=False)
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.email = self.cleaned_data['email']

            if commit:
                user.save()
            return user


class ChangePaymentForm(forms.Form):
    payment = forms.IntegerField()


class AddShifts(forms.Form):
    DAYS = (('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'),('06', '06'), ('07', '07'), ('08', '08'),
            ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'),
            ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'),
            ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'),
            ('30', '30'), ('31', '31'))
    MONTH = (('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('07', '07'), ('08', '08'),
             ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'))
    YEAR = (('20', '20'), ('21', '21'))
    day = forms.IntegerField(widget=forms.Select(choices=DAYS))
    month = forms.IntegerField(widget=forms.Select(choices=MONTH))
    year = forms.IntegerField(widget=forms.Select(choices=YEAR))
    start = forms.CharField(max_length=6, help_text="Example: 07:00")
    over = forms.CharField(max_length=6, help_text="Example: 19:00")
    PERCENT100 =  (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')
                   , ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'))
    PERCENT125 = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'))
    PERCENT150 = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')
                   , ('9', '9'))
    PERCENT175 = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'))
    PERCENT200 = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'))
    percent100 = forms.IntegerField(widget=forms.Select(choices=PERCENT100), initial=9)
    percent125 = forms.IntegerField(widget=forms.Select(choices=PERCENT125), initial=2)
    percent150 = forms.IntegerField(widget=forms.Select(choices=PERCENT150), initial=1)
    percent175 = forms.IntegerField(widget=forms.Select(choices=PERCENT175))
    percent200 = forms.IntegerField(widget=forms.Select(choices=PERCENT200))
    bonus = forms.IntegerField(initial=0)
    CHOICES = [('yes', 'Yes'),
               ('no', 'No')]
  #  rest = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect, label= "Does your employer pay you for rest ?")
    comment = forms.CharField(required=False)


class ChooseMonth(forms.Form):
    MONTH = (('1', 'January-1'), ('2', 'February-2'), ('3', 'March-3'), ('4', 'April-4'), ('5', 'May-5'),
             ('6', 'June-6'), ('7', 'July-7'), ('8', 'August-8'),('9', 'September-9'), ('10', 'October-10')
            , ('11', 'November-11'), ('12', 'December-12'))
    month = forms.IntegerField(widget=forms.Select(choices=MONTH))


class RemoveShifts(forms.Form):
    def __init__(self, set1, *args, **kwargs):
        super(RemoveShifts, self).__init__(*args, **kwargs)
        self.fields['dates'].queryset = set1

    dates = forms.ModelChoiceField(queryset=Shifts.objects.all())

mysite/salary/views.py
from datetime import datetime
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import AnonymousUser
from django.db.models.signals import post_save
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib import messages
# import to our library
from .sqlInjectionCheck import sqlInjection
from .forms import CompleteUserForm, ProfileForm, LoginForm, ChangePaymentForm, AddShifts, ChooseMonth, RemoveShifts
from .models import UserProfile, User, Shifts



def index(request):
    context = {}
    if request.user is not None:
        context['user'] = request.user
        try:
            up1 = UserProfile.objects.get(user=request.user)
            context['up1'] = up1
        except (TypeError, UserProfile.DoesNotExist):
            error = "UserProfile deletion failed."
            render(request, 'salary/index.html', {'error': error})

    return render(request, 'salary/index.html', context)



def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            u = form.cleaned_data['user_name']
            p = form.cleaned_data['password']
            u1, p1 = sqlInjection.main(u, p)
            if u!=u1 or p!= p1:
                messages.error(request, 'Your username/password is not legal !!!')
                return HttpResponseRedirect(reverse('salary:login'))
            user = authenticate(username=u, password=p)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('salary:index'))
    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, 'salary/login.html', context) #מועבר לדף זה לאחר לחיצה על התחברות בעמוד הקודם



def new_user(request):
    if request.method == 'POST':
        user_form = CompleteUserForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            user = get_object_or_404(User, username=user_form.cleaned_data['username'])
            return HttpResponseRedirect(reverse('salary:new-profile', args=[str(user.username)])) # לחיצה על כפתור submit תעביר אותי לקישור
    else: # מכניס אותי לדף עם הקישור למטה כי הוא עדיין לא זיהה form
        user_form = CompleteUserForm()
        context = {'user_form': user_form}
        return render(request, 'salary/new-user.html', context)
    
    
def new_profile(request, username):
    def attach_user(sender, **kwargs):
        userprofile = kwargs['instance']
        userprofile.user = user
        post_save.disconnect(attach_user, sender=UserProfile)
        userprofile.save()

    if request.method == 'POST':
        user = User.objects.get(username=username)
        form = ProfileForm(request.POST)
        if form.is_valid():
            post_save.connect(attach_user, sender=UserProfile)
            form.save()
            return render(request, 'salary/index.html')
    else:
        user = User.objects.get(username=username)
        form = ProfileForm()
    context = {'user': user, 'form': form}
    return render(request, 'salary/new-profile.html', context)


def logout(request):
    request.session.flush()
    if hasattr(request, 'user'):
        request.user = AnonymousUser()
    return HttpResponseRedirect(reverse('salary:index'))


def change_payment(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePaymentForm(request.POST)
        if form.is_valid():
            payment = form.cleaned_data['payment']
            user_profile = UserProfile.objects.get(user=user)
            user_profile.payment = payment
            user_profile.save()
            return HttpResponseRedirect(reverse('salary:index'))
    else:
        form = ChangePaymentForm()
    context = {'form': form}
    return render(request, 'salary/change-payment.html', context)


def add_shifts(request):
    user = request.user
    if request.method == 'POST':
        form = AddShifts(request.POST)
        if form.is_valid():
            day = form.cleaned_data.get('day')
            month = form.cleaned_data.get('month')
            year = form.cleaned_data.get('year')
            start = form.cleaned_data.get('start')
            over = form.cleaned_data.get('over')
            percent100 = form.cleaned_data.get('percent100')
            percent125 = form.cleaned_data.get('percent125')
            percent150 = form.cleaned_data.get('percent150')
            percent175 = form.cleaned_data.get('percent175')
            percent200 = form.cleaned_data.get('percent200')
            rest = form.cleaned_data.get('rest')
            bonus = form.cleaned_data.get('bonus')
            comment = form.cleaned_data.get('comment')
            up1 = UserProfile.objects.get(user=request.user)
            if month == 2 and (day == 29 or day == 30 or day == 31):
                return render(request, 'nail/not-success.html')
            elif month == 4 and day == 31:
                return render(request, 'nail/not-success.html')
            elif month == 6 and day == 31:
                return render(request, 'nail/not-success.html')
            elif month == 9 and day == 31:
                return render(request, 'nail/not-success.html')
            elif month == 11 and day == 31:
                return render(request, 'nail/not-success.html')
            else:
                date = '{0}/{1}/{2}'.format(month, day, year)
                date_object = datetime.strptime(date, '%m/%d/%y')
                time = datetime.strptime(start, '%H:%M').time()
                time_over = datetime.strptime(over, '%H:%M').time()
                shift = Shifts(date=date_object, start=time, over=time_over, user=up1)
                shift.percent100 = percent100
                shift.percent125 = percent125
                shift.percent150 = percent150
                shift.percent175 = percent175
                shift.percent200 = percent200
                shift.bonus = bonus
                shift.comment = comment
                shift.rest = rest
                total = abs(datetime.strptime(str(time_over), '%H:%M:%S') - datetime.strptime(str(time), '%H:%M:%S'))
                shift.total_time = total.seconds/60/60
                if (shift.percent100+shift.percent125+shift.percent150+shift.percent175+shift.percent200) - shift.total_time<=-1 and shift.total_time < 12:
                    return render(request, 'salary/not-success-total-time.html')
                else:
                    if shift.total_time>12:
                        shift.total_time = percent100+0.25
                    left = shift.total_time - (shift.percent100 + shift.percent125 + shift.percent150 + shift.percent175 + shift.percent200)
                    if left < 0:
                        left = left*-1
                    if shift.percent100 > 0 and shift.percent100 >= 9:
                        shift.total_money = up1.payment*percent100+up1.payment*1.25*percent125+up1.payment*1.5*percent150+shift.bonus+up1.payment*1.5*left
                    elif shift.percent100 > 0 and shift.percent100 < 9:
                        shift.total_money = up1.payment * percent100 + up1.payment * 1.25 * percent125 + up1.payment * 1.5 * percent150 + shift.bonus + up1.payment * left
                    else:
                        shift.total_money = up1.payment*1.5 * percent150 + up1.payment * 1.75 * percent175 + up1.payment * 2 * percent200 + shift.bonus + up1.payment * 2 * left
                shift.save()
                return HttpResponseRedirect(reverse('salary:index'))
    else:
        form = AddShifts()
    context = {'form': form}
    return render(request, 'salary/add-shifts.html', context)


def not_success(request):
    return render(request, 'salary/not-success-total-time.html')


def choose_month(request):
    user = request.user
    if request.method == 'POST':
        form = ChooseMonth(request.POST)
        if form.is_valid():
            month = form.cleaned_data.get('month')
            up1 = UserProfile.objects.get(user=user)
            return my_shifts(request, month)
    else:
        form = ChooseMonth()
    context = {'form': form}
    return render(request, 'salary/choose-month.html', context)



def my_shifts(request, month):
    user = request.user
    up1 = UserProfile.objects.get(user=user)
    shifts = Shifts.objects.all()
    total = 0
    bonus = 0
    days = 0
    hours = 0
    base_salary = 0
    cal100 = 0
    cal125 = 0
    cal150 = 0
    cal175 = 0
    cal200 = 0
    for i in shifts:
        if i.date.month == month and i.user == up1:
            days = days + 1
            total = total + i.total_money
            bonus = bonus + i.bonus
            hours = hours + i.total_time
            base_salary = base_salary + (i.total_money - i.bonus)
            cal100 = cal100 + i.percent100
            cal125 = cal125 + i.percent125
            cal150 = cal150 + i.percent150
            cal175 = cal175 + i.percent175
            cal200 = cal200 + i.percent200
    leumi_insurance = total * 0.0355
    health_insurance = total * 0.03
    net_salary = total - leumi_insurance - health_insurance
    context = {'up1': up1, 'shifts': shifts, 'month': month, 'total': total,
               'bonus': bonus, 'leumi': leumi_insurance, 'health': health_insurance,
               'days': days, 'hours': hours, 'base': base_salary, 'net': net_salary,
               'cal100': cal100, 'cal125': cal125, 'cal150': cal150, 'cal175': cal175, 'cal200': cal200,}
    return render(request, 'salary/my-shifts.html', context)


def remove_shifts(request):
    user = request.user
    up1 = UserProfile.objects.get(user=user)
    shifts = Shifts.objects.filter(user=up1)
    if request.method == 'POST':
        form = RemoveShifts(shifts, request.POST)
        if form.is_valid():
            if "_make-unique" in request.POST:
                dates = form.cleaned_data.get('dates')

mysite/salary/templates/salary/SubPage.html
{% load static %}


<html lang="en">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

     <!-- Site Metas -->
    <title>Salary - Rotem Librati</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'salary/images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'salary/images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'salary/css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'salary/style.css' %}">
    <!-- Colors CSS -->
    <link rel="stylesheet" href="{% static 'salary/css/colors.css' %}">
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="{% static 'salary/css/versions.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'salary/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'salary/css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="barber_version">

    <!-- LOADER -->
    <div id="preloader">
        <div class="cube-wrapper">
		  <div class="cube-folding">
			<span class="leaf1"></span>
			<span class="leaf2"></span>
			<span class="leaf3"></span>
			<span class="leaf4"></span>
		  </div>
		  <span class="loading" data-name="Loading">Salary Loading</span>
		</div>
    </div><!-- end loader -->
    <!-- END LOADER -->

    <div id="wrapper">

        <!-- Sidebar-wrapper -->
        <div id="sidebar-wrapper">
			<div class="side-top">
				<div class="logo-sidebar">
					<a href="{% url 'salary:index' %}"><img src="{% static 'salary/image/coin-stack.png' %}" alt="image"></a>
				</div>
				<ul class="sidebar-nav">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'salary:choose-month' %}">My Shifts</a></li>
					<li><a href="{% url 'salary:add-shifts' %}">Add Shifts</a></li>
					<li><a href="{% url 'salary:remove-shifts' %}">Remove Shifts</a></li>
                    <li><a href="{% url 'salary:change-payment' %}">Change Your Payment</a></li>
                    <li><a class="active" href="{% url 'salary:logout' %}">Logout</a></li>
                    {% endif %}

				</ul>
			</div>
        </div>
        <!-- End Sidebar-wrapper -->



            <section class="section nopad cac text-center">
                    <a href="#"><h3>Welcome to page of Rotem Librati</h3></a>
            </section>


            <div id="services" class="section lb">
                <div class="container-fluid">
                    <div class="section-title row text-center">
                        <div class="col-md-8 col-md-offset-2">{% block title %} {% endblock %}
                        <hr class="grd1"><h3></h3>{% block data %} {% endblock %}
                        <p class="lead"></p>

                        </div>
                    </div><!-- end title -->



                    <hr class="invis4">

                    <div class="text-center">
                        {% block text %} {% endblock %}
                    </div>
                </div><!-- end container -->
            </div><!-- end section -->



        </div>
    </div><!-- end wrapper -->

    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>

    <!-- ALL JS FILES -->
    <script src="{% static 'salary/js/all.js' %}"></script>
	<script src="{% static 'salary/js/responsive-tabs.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'salary/js/custom.js' %}"></script>

    <!-- Menu Toggle Script -->
    <script>
    (function($) {
        "use strict";
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
        smoothScroll.init({
            selector: '[data-scroll]', // Selector for links (must be a class, ID, data attribute, or element tag)
            selectorHeader: null, // Selector for fixed headers (must be a valid CSS selector) [optional]
            speed: 500, // Integer. How fast to complete the scroll in milliseconds
            easing: 'easeInOutCubic', // Easing pattern to use
            offset: 0, // Integer. How far to offset the scrolling anchor location in pixels
            callback: function ( anchor, toggle ) {} // Function to run after scrolling
        });
    })(jQuery);
    </script>

</body>
</html>

mysite/salary/templates/salary/add-shifts.html
{% extends 'salary/SubPage.html' %}
{% block title %}
<h3>Input your shift's details</h3>
{% endblock %}

{% block data %}
<form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
    <div>
        <button type="submit" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Add</button>
        <a href="{% url 'salary:index' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Back </a>
        </div>
    </form>

{% endblock %}

mysite/salary/templates/salary/change-payment.html
{% extends 'salary/SubPage.html' %}
{% block title %}
<h3>Change your payment for hour</h3>
{% endblock %}
{% block data %}
<form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Save</button>
        <a href="{% url 'salary:index' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Back </a>
    </form>
{% endblock %}

mysite/salary/templates/salary/choose-month.html
{% extends 'salary/SubPage.html' %}
{% block title %}
<h3>Choose month</h3>
{% endblock %}

{% block data %}
<form action="{% url 'salary:choose-month' %} " method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1"> Submit </button>
        <a href="{% url 'salary:index' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Back </a>
    </form>

{% endblock %}

mysite/salary/templates/salary/index.html
{% extends 'salary/SubPage.html' %}




    <title>Salary - Rotem Librati</title>





        {% block title %}
                        <h3>My Salary</h3>
        {% endblock %}

            {% block data %}

                        {% if user.is_authenticated %}
                                <h1>Hi {{ up1 }} and welcome </h1>
                                <h2>Your payment for hour is: {{ up1.payment }} </h2>
                            <a href="{% url 'salary:logout' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Logout</a>
                            <a href="{% url 'salary:choose-month' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">My Shifts</a>
                        {% endif %}
                        {% if not user.is_authenticated %}
<!--                            {% if  alert != null  %}-->
                                <h1>a</h1>
<!--                            {% endif %}-->
                            <a href="{% url 'salary:new-user' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Registration</a>
                            <a href="{% url 'salary:login' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Login</a>
                        {% endif %}
  {% endblock %}

mysite/salary/templates/salary/login.html
{% extends 'salary/SubPage.html' %}
{% block title %}
    <h3>Login</h3>
<h4>
    {% if messages %}
    {% for message in messages %}
        <div style="color:Red;" class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
</h4>
{% endblock %}

{% block data %}
    <form method="POST">

        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Login</button>
        <a href="{% url 'salary:index' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Back </a>
    </form>

{% endblock %}

mysite/salary/templates/salary/my-shifts.html
{% extends 'salary/SubPage.html' %}
{% block title %}
<h3>My shifts</h3>
{% endblock %}

{% block data %}
<h2>hi {{ up1 }} Your shifts for this month</h2>
<h2>Your shifts for month {{ month }}:</h2>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 50%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 4px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>
<table>
  <tr>
    <th>Day</th>
    <th>Start</th>
    <th>Over</th>
    <th>Hours</th>
    <th>Payment</th>
  </tr>
  <tr>
    {% for shifts in shifts %}
        {% if shifts.date.month == month %}
            {% if shifts.user == up1 %}
            <tr>
                <td>{{ shifts.date }}</td>
                <td>{{ shifts.start }}</td>
                <td>{{ shifts.over }}</td>
                <td>{{ shifts.total_time }}</td>
                <td>{{ shifts.total_money }}</td>
            </tr>
            {% endif %}
        {% endif %}
    {% endfor %}
   <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>total: {{ total }}</td>
          </tr>
  </tr>
</table>
<h2><u>Salary</u></h2>
<li>Base Salary: {{ base }}</li>
<li>Bonus: {{ bonus }} </li>
<li>Gross salary:  {{ total }} </li>
<h2><u>Compulsory Deductions</u></h2>
<li>Leumi insurance: {{ leumi }} </li>
<li>Health insurance: {{ health }} </li>

<h1><b>Net Salary: {{ net }}</b></h1>
<h2><u>Monthly Summary</u></h2>
<li>Work days {{ days }}</li>
<li>Total hours {{ hours }}</li>

<h2><u>Tariff Details</u></h2>
<li>100% - total hours: {{ cal100 }} </li>
<li>125% - total hours: {{ cal125 }} </li>
<li>150% - total hours: {{ cal150 }} </li>
<li>175% - total hours: {{ cal175 }} </li>
<li>200% - total hours: {{ cal200 }} </li>
<h4>Total: {{ hours }} </h4>
    <a data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1" href="{% url 'salary:index' %}">Index </a>
</body>
</html>
{% endblock %}

mysite/salary/templates/salary/new-profile.html
{% extends 'salary/SubPage.html' %}
{% block title %}
<h3>Page 2</h3>
{% endblock %}
{% block data %}
    <form action="{% url 'salary:new-profile' user.username %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Finish registration</button>

</form>
{% endblock %}

mysite/salary/templates/salary/new-user.html
{% extends 'salary/SubPage.html' %}
{% block title %}
    <h3>New User</h3>
{% endblock %}
{% block data %}
    <form action="{% url 'salary:new-user' %} " method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        <button type="submit" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1"> Submit </button>
        <a href="{% url 'salary:index' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Back </a>
    </form>

{% endblock %}

mysite/salary/templates/salary/not-success-total-time.html
<!DOCTYPE html>
<html lang="en">
<head>
    Your total time does not match to hours
    <a href="{% url 'salary:add-shifts' %}">back </a>
</head>
<body>

</body>
</html>

mysite/salary/templates/salary/remove-shifts.html
{% extends 'salary/SubPage.html' %}
{% block title %}
<h3>Choose date for remove </h3>
{% endblock %}

{% block data %}
    <form action="{% url 'salary:remove-shifts' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1" value="Delete" name="_make-unique">
  <a href="{% url 'salary:index' %}" data-scroll class="btn btn-light btn-radius btn-brd grd1 effect-1">Back </a>

</form>
{% endblock %}